---
# defaults file for common
# The name of ssh daemon
sshd: ssh

# Where is ssh config is located at
sshd_config: /etc/ssh/sshd_config

# Defaults for Elastic Beats
elk_version: 6.6.0

# Filebeat Parameters
filebeat_version: 6.x
filebeat_create_config: true

filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "localhost:9200"

beat_output_logstash_enabled: true
beat_output_logstash_hosts:
  - "172.104.228.223:5044"

filebeat_enable_logging: true
filebeat_log_level: warning
filebeat_log_dir: /var/log/beats
filebeat_log_filename: filebeat.log
metricbeat_log_filename: metricbeat.log

filebeat_ssl_dir: /etc/pki/logstash
filebeat_ssl_certificate_file: ""
filebeat_ssl_key_file: ""
filebeat_ssl_insecure: "false"

# Filebeat Inputs
filebeat_inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
  - type: docker
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    containers.ids: '*'

# Metricbeat Modules
metricbeat_modules:
- module: system
  metricsets:
    - cpu             # CPU usage
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - core           # Per CPU core usage
    - diskio         # Disk IO
    - filesystem     # File system usage for each mountpoint
    - fsstat         # File system summary metrics
    #- raid           # Raid
    #- socket         # Sockets and connection info (linux only)
  enabled: true
  period: 10s
  processes: ['.*']

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true


