---
# tasks file for common
- name: Update apt-cache and install basic packages
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
    - aptitude
    - apt-transport-https
    - ca-certificates 
    - curl
    - gnupg-agent
    - software-properties-common
    - git

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

#https://stackoverflow.com/questions/35991247/apt-repository-module-fails-ansible
- name: Run command for cleanup
  command: apt-get -y clean && apt-get -y autoclean
  become: yes

- include: monitoring.yml
- include: security.yml

